//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThornWriter {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ThornWriter.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        internal static string DocumentBase {
            get {
                return ResourceManager.GetString("DocumentBase", resourceCulture);
            }
        }
        
        internal static string DocumentStyle {
            get {
                return ResourceManager.GetString("DocumentStyle", resourceCulture);
            }
        }
        
        internal static string TextEdit {
            get {
                return ResourceManager.GetString("TextEdit", resourceCulture);
            }
        }
        
        internal static string TextEditStyle {
            get {
                return ResourceManager.GetString("TextEditStyle", resourceCulture);
            }
        }
        
        internal static string TextEditScript {
            get {
                return ResourceManager.GetString("TextEditScript", resourceCulture);
            }
        }
        
        internal static string CodeMirrorStyle {
            get {
                return ResourceManager.GetString("CodeMirrorStyle", resourceCulture);
            }
        }
        
        internal static string CodeMirrorThemeAyuMirage {
            get {
                return ResourceManager.GetString("CodeMirrorThemeAyuMirage", resourceCulture);
            }
        }
        
        internal static string CodeMirrorThemeBase16Dark {
            get {
                return ResourceManager.GetString("CodeMirrorThemeBase16Dark", resourceCulture);
            }
        }
        
        internal static string CodeMirrorThemeTtcn {
            get {
                return ResourceManager.GetString("CodeMirrorThemeTtcn", resourceCulture);
            }
        }
        
        internal static string CodeMirrorScript {
            get {
                return ResourceManager.GetString("CodeMirrorScript", resourceCulture);
            }
        }
        
        internal static string CodeMirrorModeCss {
            get {
                return ResourceManager.GetString("CodeMirrorModeCss", resourceCulture);
            }
        }
        
        internal static string CodeMirrorModeHtmlMixed {
            get {
                return ResourceManager.GetString("CodeMirrorModeHtmlMixed", resourceCulture);
            }
        }
        
        internal static string CodeMirrorModeJs {
            get {
                return ResourceManager.GetString("CodeMirrorModeJs", resourceCulture);
            }
        }
        
        internal static string CodeMirrorModeXml {
            get {
                return ResourceManager.GetString("CodeMirrorModeXml", resourceCulture);
            }
        }
    }
}
